services:
  - type: web
    name: robotica-lab-v9
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ARDUINO_UPDATER_ENABLE_NOTIFICATION
        value: "false"
